version: '3'
services:
  client:
    build: ./client
    ports:
      - "8080:5000"
  server:
    build: ./server
    ports:
      - "8081:5000"
    networks:
      - mongo_net
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge